export const UserLoginTypes = {
    LOGIN_USER : 'LOGIN_USER',
    LOGIN_USER_FULFILLED : 'LOGIN_USER_FULFILLED',
    LOGIN_USER_REJECTED : 'LOGIN_USER_REJECTED'
}

export const UserRegisterTypes = {
    REGISTER_USER : 'REGISTER_USER',
    REGISTER_USER_FULFILLED : 'REGISTER_USER_FULFILLED',
    REGISTER_USER_REJECTED : 'REGISTER_USER_REJECTED'
}